### ISSUE TITLE
 example.ino:2:20: fatal error: cc1101.h: No such file or directory compilation terminated.

### ISSUE THREAD

**Issue by guitar9** [veonik/arduino-cc1101#14]
example.ino:2:20: fatal error: cc1101.h: No such file or directory
compilation terminated.

I added this repo as zip. I get this error. What should i include?

**Comment by guitar9** [comment]
download it here and include this library. https://www.electrodragon.com/w/File:Panstamp.zip

**Comment by mirisuort** [comment]
Hi! The page has been deleted. Where can I find the library? Thank you!

**Comment by tyler-sommer** [comment]
@mirisuort cc1101.h is included with the arduino-cc1101 library: https://raw.githubusercontent.com/veonik/arduino-cc1101/master/src/cc1101.h
