### ISSUE TITLE
This Libary does not work anymore

### ISSUE THREAD

**Issue by guitar9** [veonik/arduino-cc1101#15]
I tried to get it run at Arduino Mega. 
 I have a cc1101 with 868 mhz. And I want to log the informations from a MAX! thermostat. 
When i want to run this programm I get only 

CC1101_PARTNUM 0
CC1101_VERSION 20
CC1101_MACSTATE 9
CC1101 radio initialized

Somebody can help me?

**Comment by tyler-sommer** [comment]
Hi @guitar9 , I was able to get this library working with my Mega, but different pins must be used. [By default](https://github.com/veonik/arduino-cc1101/blob/master/examples/example/example.ino#L13-L15), you need to change GDO0 from pin 2 to pin 19 and then wire up the remaining SPI pins appropriately for the Mega (See https://www.arduino.cc/en/Reference/SPI and https://forum.arduino.cc/index.php?topic=413494.0).

I'll close this now, but please open another issue as you please! Thanks!
